Option for number of characters between whitespaces added

diff --git a/asciiBackup b/asciiBackup
--- a/asciiBackup
+++ b/asciiBackup
@@ -101,6 +101,20 @@ case $key in
 		shift
 		shift
 		;;
+	-g|--group-size)
+		if [[ $GROUPSIZE ]]; then
+			echo "Error: Ambigious specification of group size."
+			exit 1
+		fi
+		if is_integer $2; then
+			GROUPSIZE=$2
+		else
+			echo "'$2' is not a valid integer."
+			exit 1
+		fi
+		shift
+		shift
+		;;
 	*) # positional argument or unknown option
 		if [[ "${1:0:1}" == "-" ]]; then
 			echo "Unknown option '$1'."
@@ -125,4 +139,7 @@ if [[ ! $ENCFUNC ]]; then
 fi
 if [[ ! $COLS ]]; then
 	COLS=36
+fi
+if [[ ! $GROUPSIZE ]]; then
+	GROUPSIZE=6
 fi
